spartan-stratos/terraform-modules

aws/acm/README.md
aws/alb/README.md
aws/amplify/README.md
aws/ecr/README.md
aws/ecs-application/README.md
aws/ecs-cluster/README.md
aws/eks-cluster/README.md
aws/elasticache/README.md
aws/opensearch/README.md
aws/password-generator/README.md
aws/postgres/README.md
aws/route53/README.md
aws/s3/README.md
aws/sqs/README.md
aws/ssm-parameter/README.md
aws/static-website/README.md
aws/static-website/modules/cloudfront/README.md
aws/vpc-endpoints/README.md
aws/vpc/README.md
aws/vpn/README.md

Fix the typo of example module source
N/A
N/A

feat: update example module source

---

gcp/postgresql/CHANGELOG.md
gcp/postgresql/README.md
gcp/postgresql/examples/complete/README.md
gcp/postgresql/examples/complete/main.tf
gcp/postgresql/examples/complete/outputs.tf
gcp/postgresql/locals.tf
gcp/postgresql/main.tf
gcp/postgresql/outputs.tf
gcp/postgresql/variables.tf
gcp/postgresql/versions.tf
gcp/redis-cluster/CHANGELOG.md
gcp/redis-cluster/README.md
gcp/redis-cluster/examples/complete/README.md
gcp/redis-cluster/examples/complete/main.tf
gcp/redis-cluster/examples/complete/outputs.tf
gcp/redis-cluster/main.tf
gcp/redis-cluster/outputs.tf
gcp/redis-cluster/variables.tf
gcp/redis-cluster/versions.tf
gcp/vpc/CHANGELOG.md
gcp/vpc/README.md
gcp/vpc/examples/complete/README.md
gcp/vpc/examples/complete/main.tf
gcp/vpc/examples/complete/outputs.tf
gcp/vpc/main.tf
gcp/vpc/outputs.tf
gcp/vpc/variables.tf
gcp/vpc/versions.tf

Add GCP modules: vpc, redis cluster, postgresql.

Add GCP modules: vpc, redis cluster, postgresql

---

CHANGELOG.md

Create change log 0.1.1
N/A
N/A

changelog 0.1.1

---

aws/static-website/CHANGELOG.md
aws/static-website/README.md
aws/static-website/cloudfront.tf
aws/static-website/modules/cloudfront/README.md
aws/static-website/modules/cloudfront/main.tf
aws/static-website/modules/cloudfront/variables.tf
aws/static-website/variables.tf

Update Static website:
- Add more variables to make this module generally
- Default policy is redirect HTTP to HTTPS
N/A
N/A

feat: update static-website module

---

CHANGELOG.md

feat: change log 0.1.2

---

gcp/service-account/CHANGELOG.md
gcp/service-account/README.md
gcp/service-account/examples/complete/README.md
gcp/service-account/examples/complete/main.tf
gcp/service-account/examples/complete/outputs.tf
gcp/service-account/locals.tf
gcp/service-account/main.tf
gcp/service-account/outputs.tf
gcp/service-account/variables.tf
gcp/service-account/versions.tf

Init GCP Service Account module. Release on next `v0.1.3`.
1. Check plan

Init GCP Service Account module

---

gcp/gke-gateway-api/CHANGELOG.md
gcp/gke-gateway-api/README.md
gcp/gke-gateway-api/examples/complete/README.md
gcp/gke-gateway-api/examples/complete/main.tf
gcp/gke-gateway-api/examples/complete/outputs.tf
gcp/gke-gateway-api/main.tf
gcp/gke-gateway-api/outputs.tf
gcp/gke-gateway-api/variables.tf
gcp/gke-gateway-api/versions.tf

Init GCP GKE Gateway API module. Release on next `v0.1.3`.
1. Check plan

Init GCP GKE Gateway API module

---

gcp/github-oidc/CHANGELOG.md
gcp/github-oidc/README.md
gcp/github-oidc/examples/complete/README.md
gcp/github-oidc/examples/complete/main.tf
gcp/github-oidc/examples/complete/outputs.tf
gcp/github-oidc/main.tf
gcp/github-oidc/outputs.tf
gcp/github-oidc/variables.tf
gcp/github-oidc/versions.tf

Init GCP Github OIDC. Release on next `v0.1.3`.
1. Check plan

Init GCP Github OIDC

---

CHANGELOG.md

Release these features
* Add GCP Github OIDC
* Add GCP GKE Gateway API module
* Add GCP Service Account module
* Add AWS Eventbridge Scheduler module

Update changelog to 0.1.3

---

CHANGELOG.md
gcp/wildcard-sslcert/CHANGELOG.md
gcp/wildcard-sslcert/README.md
gcp/wildcard-sslcert/certmap.tf
gcp/wildcard-sslcert/examples/completes/README.md
gcp/wildcard-sslcert/examples/completes/main.tf
gcp/wildcard-sslcert/examples/completes/outputs.tf
gcp/wildcard-sslcert/main.tf
gcp/wildcard-sslcert/outputs.tf
gcp/wildcard-sslcert/variables.tf
gcp/wildcard-sslcert/versions.tf

Add new module gcp/wildcard-sslcert
Add new module gcp/wildcard-sslcert
Add new module gcp/wildcard-sslcert

Feat: Module gcp/wildcard-sslcert

---

gcp/project-service/CHANGELOG.md
gcp/project-service/README.md
gcp/project-service/examples/complete/README.md
gcp/project-service/examples/complete/main.tf
gcp/project-service/main.tf
gcp/project-service/variables.tf
gcp/project-service/versions.tf

Init GCP project service. Release version `v0.1.5`.

Init GCP project service

---

gcp/storage-bucket/CHANGELOG.md
gcp/storage-bucket/README.md
gcp/storage-bucket/examples/complete/README.md
gcp/storage-bucket/examples/complete/main.tf
gcp/storage-bucket/examples/complete/outputs.tf
gcp/storage-bucket/iam.tf
gcp/storage-bucket/main.tf
gcp/storage-bucket/outputs.tf
gcp/storage-bucket/variables.tf
gcp/storage-bucket/versions.tf

Init GCP storage bucket. Release version `v0.1.5`.

Init GCP storage bucket

---

gcp/workload-identity/CHANGELOG.md
gcp/workload-identity/README.md
gcp/workload-identity/data.tf
gcp/workload-identity/examples/complete/README.md
gcp/workload-identity/examples/complete/main.tf
gcp/workload-identity/examples/complete/outputs.tf
gcp/workload-identity/main.tf
gcp/workload-identity/outputs.tf
gcp/workload-identity/variables.tf
gcp/workload-identity/versions.tf

Init GCP workload identity. Release version `v0.1.5`.

Init GCP workload identity

---

README.md
gcp/service-config/CHANGELOG.md
gcp/service-config/README.md
gcp/service-config/dns.tf
gcp/service-config/examples/complete/README.md
gcp/service-config/examples/complete/main.tf
gcp/service-config/examples/complete/outputs.tf
gcp/service-config/kubernetes.tf
gcp/service-config/outputs.tf
gcp/service-config/service-account.tf
gcp/service-config/variables.tf
gcp/service-config/versions.tf

Init GCP service config. Release version `v0.1.5`.
Update `README.md` with terraform-docs to support module documentation.

Init GCP service config

---

gcp/gke-ingress/CHANGELOG.md
gcp/gke-ingress/README.md
gcp/gke-ingress/examples/complete/README.md
gcp/gke-ingress/examples/complete/main.tf
gcp/gke-ingress/examples/complete/outputs.tf
gcp/gke-ingress/locals.tf
gcp/gke-ingress/main.tf
gcp/gke-ingress/outputs.tf
gcp/gke-ingress/variables.tf
gcp/gke-ingress/versions.tf

Init GCP GKE Ingress module. Release `v0.1.5`.
1. Check plan

Init GCP GKE Ingress module

---

gcp/google-workspace/CHANGELOG.md
gcp/google-workspace/README.md
gcp/google-workspace/examples/complete/README.md
gcp/google-workspace/examples/complete/main.tf
gcp/google-workspace/main.tf
gcp/google-workspace/modules/group/README.md
gcp/google-workspace/modules/group/main.tf
gcp/google-workspace/modules/group/variables.tf
gcp/google-workspace/modules/group/versions.tf
gcp/google-workspace/variables.tf
gcp/google-workspace/versions.tf

Init GCP workspace module. Release `v0.1.5`.
1. Check plan

Init GCP workspace module

---

gcp/service-connection-policies/CHANGELOG.md
gcp/service-connection-policies/README.md
gcp/service-connection-policies/examples/complete/README.md
gcp/service-connection-policies/examples/complete/main.tf
gcp/service-connection-policies/main.tf
gcp/service-connection-policies/variables.tf
gcp/service-connection-policies/versions.tf

Init GCP service connection policies module. Release `v0.1.5`.
1. Check plan

Init GCP service connection policies module

---

gcp/openvpn/CHANGELOG.md
gcp/openvpn/README.md
gcp/openvpn/examples/complete/main.tf
gcp/openvpn/examples/complete/outputs.tf
gcp/openvpn/firewall.tf
gcp/openvpn/locals.tf
gcp/openvpn/main.tf
gcp/openvpn/outputs.tf
gcp/openvpn/scripts/install_openvpn.sh
gcp/openvpn/tls.tf
gcp/openvpn/variables.tf
gcp/openvpn/versions.tf

Create the Terraform module for GCP OpenVPN for internal VPN network access
N/A

Init OpenVPN GCP Module

---

CHANGELOG.md

Update changelog v0.1.5

---

CHANGELOG.md
gcp/service-config/CHANGELOG.md
gcp/service-config/dns.tf
gcp/service-config/outputs.tf

* Fixed a bug where the output `dns_record_name` could be null if the `managed_zone` was not specified.
* Fixed a bug that prevented the creation of the DNS record set due to an incorrect DNS name value
Bug 1: Using try block
Bug 2: Using host_name and domain_name
- TF applied success

Fix: Bug on service-config module

---

CHANGELOG.md
aws/ses/CHANGELOG.md
aws/ses/README.md
aws/ses/examples/complete/main.tf
aws/ses/main.tf
aws/ses/outputs.tf
aws/ses/variables.tf

Fix the SES policy to send the email
- We can create the SES identity
- We can send the email from SES verified domain
N/A

bug: update ses

---

CHANGELOG.md
aws/schedulers/CHANGELOG.md
aws/schedulers/README.md
aws/schedulers/main.tf
aws/schedulers/variables.tf

Remove schedule_expression by default and add it to variable

Refactor eventbridge module

---

aws/kms/CHANGELOG.md
aws/kms/README.md
aws/kms/examples/complete/main.tf
aws/kms/examples/complete/outputs.tf
aws/kms/main.tf
aws/kms/output.tf
aws/kms/variables.tf

Refactor some variables and update README.md
Make the Terraform modules more general to use.
N/A
https://www.notion.so/c0x12c/Infra-Centralized-Terraform-Modules-12d01fb05bf18006867df82b37b3fb32?pvs=4

Refactor KMS modules

---

CHANGELOG.md

Release changelog v0.1.9

---

github/actions/CHANGELOG.md
github/actions/README.md
github/actions/examples/action-secrets/README.md
github/actions/examples/action-secrets/main.tf
github/actions/examples/action-variables/README.md
github/actions/examples/action-variables/main.tf
github/actions/examples/complete/README.md
github/actions/examples/complete/main.tf
github/actions/main.tf
github/actions/modules/action-secrets/README.md
github/actions/modules/action-secrets/main.tf
github/actions/modules/action-secrets/variables.tf
github/actions/modules/action-secrets/versions.tf
github/actions/modules/action-variables/README.md
github/actions/modules/action-variables/main.tf
github/actions/modules/action-variables/variables.tf
github/actions/modules/action-variables/versions.tf
github/actions/variables.tf
github/actions/versions.tf

Add GitHub Actions modules. Release `v0.1.10`.
1. Check plan

Add GitHub Actions modules

---

CHANGELOG.md

Changelog v0.1.10

---

aws/cloudwatch/alarm/CHANGELOG.md
aws/cloudwatch/alarm/README.md
aws/cloudwatch/alarm/examples/complete/README.md
aws/cloudwatch/alarm/examples/complete/main.tf
aws/cloudwatch/alarm/main.tf
aws/cloudwatch/alarm/variables.tf
aws/cloudwatch/alarm/versions.tf

Setup module cloudwatch alarm (for soc2 requirements (from Triangle)
Setup Terraform modules for cloudwatch alarm
Terraform plan

Setup module cloudwatch alarm

---

CHANGELOG.md

Update changelog to 0.1.11

---

aws/acm/CHANGELOG.md
aws/acm/README.md
aws/acm/main.tf
aws/acm/variables.tf

Update AWS ACM var.zone_id default value to null and resource conditions: to create `aws_route53_record` and `aws_acm_certificate_validation` only if (and) `var.zone_id` is not null
To adapt with DAXE rollout.
https://www.notion.so/c0x12c/Daxe-15601fb05bf180a382b2e699d645e7b1?pvs=4

Update AWS ACM var.zone_id default value to null and resource conditions

---

CHANGELOG.md
aws/github-oidc/CHANGELOG.md
aws/kms/CHANGELOG.md
aws/route53/CHANGELOG.md
aws/s3/CHANGELOG.md

* Add AWS GitHub OIDC (./aws/github-oidc)
* Update output for AWS Route53 (./aws/route53)
* Add `read_write_policy` and attributes `force_destroy` for AWS S3  (./aws/s3)
* Update policy for AWS KMS (./aws/kms)
* Update AWS ACM `var.zone_id` default value to `null` and resource conditions (./aws/acm)

release: v0.1.12

---

aws/openvpn/CHANGELOG.md
aws/openvpn/README.md
aws/openvpn/instance.tf

Add the ignore_change lifecycle for AMI and UserData to prevent recreate the resources
N/A

feat: openvpn ignore change

---

CHANGELOG.md

*  OpenVPN: Add Ignore Change for `ami` and `user_data`  [(./aws/openvpn)](./aws/openvpn)
N/A

release: 0.1.13

---

aws/vpc/CHANGELOG.md
aws/vpc/README.md
aws/vpc/main.tf
aws/vpc/security-group.tf
aws/vpc/variables.tf

Update AWS VPC.
To adapt DAXE rollout.
* Add variables: `create_custom_subnets`, `custom_public_subnets`, `custom_private_subnets` and update subnet creation logics.
* Correct `aws_security_group.allow_all_within_vpc` ingress rule `cidr_blocks`.
* Remove `environment` from resource tags.
* Correct `aws_security_group.allow_all_within_vpc` ingress rule `cidr_blocks`: previously rule set to public -> correct to vpc cidr_blocks.
* Remove `environment` from resource tags: which should be overwritten by provider tags.

Update AWS VPC

---

CHANGELOG.md

* AWS Postgre: Add `var.db_identifier` and update `identifier` naming logic from modules `main_db_instance` and `replica_db_instance`. Add `var.copy_tags_to_snapshot`. [(./aws/postgres)](./aws/postgres)
* AWS VPC: Add variables: `create_custom_subnets`, `custom_public_subnets`, `custom_private_subnets` and update subnet creation logics. Correct `aws_security_group.allow_all_within_vpc` ingress rule `cidr_blocks`. Remove `environment` from resource tags.[(./aws/vpc)](./aws/vpc)
* AWS Route53: Add `r53_main_name_servers` output for route53 [(./aws/route53)](./aws/route53)

release: v0.1.14

---

aws/cloudtrail/CHANGELOG.md
aws/cloudtrail/README.md
aws/cloudtrail/data.tf
aws/cloudtrail/examples/complete/README.md
aws/cloudtrail/examples/complete/main.tf
aws/cloudtrail/main.tf
aws/cloudtrail/output.tf
aws/cloudtrail/variables.tf
aws/cloudtrail/versions.tf

Setup Cloudtrail terraform module for SOC2 requiremnent
Terraform module which creates external AWS CloudTrail resources:
- A CloudTrail to log API activity and events across your AWS account.
- An S3 bucket to store CloudTrail logs with appropriate policies.
- A CloudWatch Logs group to store and monitor CloudTrail logs.
- Optional SNS topic to notify on specific CloudTrail events.
Terraform plan

Add terraform module for CloudTrail

---

aws/postgres/CHANGELOG.md
aws/postgres/README.md
aws/postgres/locals.tf
aws/postgres/main.tf
aws/postgres/parameter_group.tf
aws/postgres/variables.tf
aws/route53/examples/complete/outputs.tf

Update AWS Postgres with security group and parameter group name overwrite.
To adapt DAXE rollout without sensitive changes or destroys.
Add variables for overwrite parameter group name and use existing security groups:
- variable "custom_parameter_group_name"
- variable "vpc_security_group_ids"

Update AWS Postgres security group and parameter group name overwrite

---

aws/kms/CHANGELOG.md
aws/kms/iam.tf
aws/kms/output.tf

Fix output contraints of KMS module

---

CHANGELOG.md

Release v0.1.15
* Add AWS Cloud Trail module [(./aws/cloudtrail)](./aws/cloudtrail).
* AWS Postgres: Update security group to use vpc existing security groups and allow user to overwrite rds parameter group name.
* AWS KMS: Change from `aws_iam_policy.this[*].arn` to `values(aws_iam_policy.this)[*].arn` in order to fix the null list output.
* AWS S3: Add variable `acl` and resource `aws_s3_bucket_acl`.

release: v0.1.15

---

aws/cloudwatch/alarm/main.tf
aws/cloudwatch/alarm/variables.tf

Introduced an optional `target_group_name` variable to support configuring target group dimensions for ApplicationELB alarms. Updated logic in `main.tf` to include this dimension when `target_group_name` is provided.
Terraform plan
N/A

Add support for specifying target group in alarms

---

aws/kms/CHANGELOG.md
aws/kms/iam.tf

Add policy to fix KMS action deploy in Atlas Project

Add policy to KMS fix problem in Atlas

---

CHANGELOG.md

* AWS Cloudwatch Alarm: Add support for specifying target group in alarms [(./aws/cloudwatch/alarm)](./aws/cloudwatch/alarm).
* AWS KMS: Add policy `kms:PutKeyPolicy` to fix cannot apply because of error KMS: PutKeyPolicy [(./aws/kms)](./aws/kms)

changelog: v0.1.16

---

aws/kms/CHANGELOG.md
aws/kms/README.md
aws/kms/iam.tf
aws/kms/variables.tf

Update KMS policy

---

aws/static-website/CHANGELOG.md
aws/static-website/README.md
aws/static-website/cloudfront.tf
aws/static-website/modules/cloudfront/README.md
aws/static-website/modules/cloudfront/main.tf
aws/static-website/modules/cloudfront/variables.tf
aws/static-website/s3.tf
aws/static-website/variables.tf

Update AWS static-website module. Release `v0.1.17`.
To adapt DAXE rollout on this module.
* Update aws_cloudfront_distribution.aliases.
* Add variables `domain_name` to root module and sub-module `cloudfront`.
* Add variables `enabled_read_write_policy`, `enabled_read_only_policy` to root module and to s3 module.

Update AWS static-website module

---

CHANGELOG.md

release: v0.1.17.
* AWS KMS: Update key policy statement [(./aws/kms)](./aws/kms).
* AWS static-website: Update `aws_cloudfront_distribution.aliases`. Add variable `domain_name`, `enabled_read_write_policy`, `enabled_read_only_policy`. [(./aws/static-website)](./aws/static-website).

release: v0.1.17

---

aws/s3/CHANGELOG.md
aws/s3/README.md
aws/s3/iam.tf
aws/s3/outputs.tf

Add S3 module outputs: iam_policy_s3_bucket_assets_read_write_arn.

Add S3 module outputs

---

CHANGELOG.md

release: v0.1.18.
* AWS S3: add output: `iam_policy_s3_bucket_assets_read_write_arn`.

release: v0.1.18

---

CHANGELOG.md

Features:
- AWS EKS: add output datadog_agent_cluster_role_name
- AWS EKS: Update assume policy of eks-node-cluster from eks.amazonaws.com to ec2.amazonaws.com

release: v0.1.19

---

CHANGELOG.md
aws/eks-helm/aws-load-balancer-controller/CHANGELOG.md

* AWS eks-helm/aws-load-balancer-controller: init module [(./aws/eks-helm/aws-load-balancer-controller)](./aws/eks-helm/aws-load-balancer-controller/)
* AWS SQS [(./aws/sqa)](./aws/sqs)
* Refactor components.
* Update policies Send Receive resources principal to created queue only.
* Update policy Receive with 2 additional permissions: `sqs:DeleteMessage`, `sqs:GetQueueAttributes`.
* Remove redundant policy in `aws_sqs_queue.queue`.

Release v0.1.20

---

aws/eks-helm/metrics-server/CHANGELOG.md
aws/eks-helm/metrics-server/README.md
aws/eks-helm/metrics-server/examples/README.md
aws/eks-helm/metrics-server/examples/main.tf
aws/eks-helm/metrics-server/main.tf
aws/eks-helm/metrics-server/variables.tf
aws/eks-helm/metrics-server/versions.tf

Add a new module: eks-helm/metrics-server to provision and configure metrics server in eks.

Add eks-helm modules - Metrics-server

---

CHANGELOG.md

* AWS EKS-Helm Metrics Server: Init module. [(./aws/eks-helm/metrics-server)](./aws/eks-helm/metrics-server)
* AWS EKS-RBAC: Init module. [(./aws/eks-rbac)](./aws/eks-rbac)
* AWS SES: Rename `use_route53` to `verify_domain` and add prefix `_amazonses.` to route53 record to validate SES domain. [(./aws/ses)](./aws/ses)
* AWS OIDC provider: refactor and generalized [(./aws/github-oidc/modules/provider)]() to dedicated module at [(./aws/oidc/provider)](./aws/oidc/provider).
* AWS Jenkins OIDC: Init jenkins-oidc module. [(aws/oidc/jenkins-oidc)](./aws/oidc/jenkins-oidc)
* AWS GitHub OIDC: [(aws/oidc/github-oidc)](./aws/oidc/github-oidc)
* Add provider `tls` version constraints.
* Replace `var.aws_account_id` with `data.aws_caller_identity` to use runtime AWS identity.
* Add variables: …

release: v0.1.21

---

README.md

fix: correct typo error in README.md
After merge: checkout this commit to branch `/gh-pages`.
To avoid confusion in naming convention.

fix: correct typo error in README.md

---

aws/cloudwatch/vpc-flow-logs/CHANGELOG.md
aws/cloudwatch/vpc-flow-logs/README.md
aws/cloudwatch/vpc-flow-logs/examples/README.md
aws/cloudwatch/vpc-flow-logs/examples/main.tf
aws/cloudwatch/vpc-flow-logs/main.tf
aws/cloudwatch/vpc-flow-logs/variables.tf
aws/cloudwatch/vpc-flow-logs/versions.tf

Terraform module which configure publishing VPC flow logs to CloudWatch Logs
https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-cwl.html

Add new module cloudwatch/vpc-flow-logs

---

aws/eks-helm/datadog/CHANGELOG.md
aws/eks-helm/datadog/README.md
aws/eks-helm/datadog/examples/README.md
aws/eks-helm/datadog/examples/main.tf
aws/eks-helm/datadog/main.tf
aws/eks-helm/datadog/outputs.tf
aws/eks-helm/datadog/variables.tf
aws/eks-helm/datadog/versions.tf

This module helps install and configure Datadog agents for EKS clusters via Helm chart.

Add new AWS Terraform module: eks-helm/datadog

---

aws/eks-service/CHANGELOG.md
aws/eks-service/README.md
aws/eks-service/examples/README.md
aws/eks-service/examples/main.tf
aws/eks-service/main.tf
aws/eks-service/outputs.tf
aws/eks-service/variables.tf
aws/eks-service/versions.tf

This module helps configure an 'EKS Service' by creating a correlation set of Kubernetes and AWS resources.

Add new AWS module - eks-service

---

aws/postgres/CHANGELOG.md
aws/postgres/README.md
aws/postgres/db_instance/outputs.tf
aws/postgres/main.tf
aws/postgres/outputs.tf
aws/postgres/variables.tf

Update some hardcode value to variables to make sure it will be general

Update hardcode values to variables

---

CHANGELOG.md

* AWS EKS-Service: Init module. [(./aws/eks-service)](./aws/eks-service)
* AWS EKS-Helm / Datadog: Init module. [(./aws/eks-helm/datadog)](./aws/eks-helm/datadog)
* AWS Amplify: [(./aws/amplify)](./aws/amplify)
* Add `var.enable_backend` to enable backend or use frontend format only
* Add `aws_amplify_webhook` to provides an Amplify Webhook resource
* AWS VPC: [(./aws/vpc)](./aws/vpc)
* Separate the VPC and Security Group
* Introduced a conditional mechanism to control the creation of VPC flow logs.
* Datadog/AWS Integration: Init module. [(./datadog/aws-integration)](./datadog/aws-integration)
* Datadog/GCP Integration: Init module. [(./datadog/gcp-integration)](./datadog/gcp-integration)
* AWS Postgres: Add `var.publicly_accessible` to allow external machine connect to rds if `true` …

Release v0.1.22

---

CHANGELOG.md

* AWS Security Group: Introduce functionality to create default security groups with configurable CIDR blocks and VPC ID.
* AWS GuardDuty: Init module.

release: v0.1.23

---

aws/s3/CHANGELOG.md
aws/s3/README.md
aws/s3/main.tf
aws/s3/variables.tf

aws/s3: add attribute expose_headers to variable cors_configuration

---

aws/elasticache/CHANGELOG.md
aws/elasticache/README.md
aws/elasticache/outputs.tf

Add configuration_endpoint_address output to `aws/elasticache` module

aws/elasticache: add configuration_endpoint_address output

---

CHANGELOG.md

* AWS EKS Service: [(./aws/eks-service)](./aws/eks-service)
* Add `var.create_kubernetes_namespace` to specify whether to create a namespace
* Add `var.config_map_env_var_name` to overwrite default kubernetes_config_map name
* Add `var.secret_env_var_name` to overwrite default kubernetes_secret secret env var name
* Add output `elasticache_replication_group_configuration_endpoint_address`. 
* AWS S3: [(./aws/s3)](./aws/s3)
* Add attribute `expose_headers` to variable `cors_configuration`.

changelog: v0.1.24

---

CHANGELOG.md

* AWS Security Group: Add variables: custom_sg_allow_all_description and custom_sg_allow_all_within_all_description to avoid forces replacement during migration. [(./aws/security-group)](./aws/security-group)

release: v0.1.25

---

aws/eks-service/CHANGELOG.md
aws/eks-service/README.md
aws/eks-service/outputs.tf

* Add output `service_hostnames` to generates a map of service hostnames by iterating over the Route 53 records and extracting their fully qualified domain names (FQDNs)

aws/eks_service: add new output for migration

---

aws/s3/CHANGELOG.md
aws/s3/README.md
aws/s3/iam.tf
aws/s3/variables.tf

* Add variables `read_write_policy_description`, `readonly_policy_description` and `readonly_policy_name_prefix` to avoid forced resource replacements during rollout.

Add variables to AWS S3 module

---

CHANGELOG.md

* AWS S3: Add variables `read_write_policy_description`, `readonly_policy_description` and `readonly_policy_name_prefix` to avoid forced resource replacements during rollout [(./aws/s3)](./aws/s3)
* AWS Security Groups: Add variable `custom_sg_allow_all_within_vpc_egress_ipv6_cidr_blocks` to avoid update sg during migration [(./aws/security-group)](./aws/security-group)

Release v0.1.27

---

aws/sqs/CHANGELOG.md
aws/sqs/README.md
aws/sqs/iam.tf
aws/sqs/variables.tf

* Add customizable prefix for read/write policy name via variables `read_policy_name_prefix` and `write_policy_name_prefix`.

aws/sqs: make prefix of read/write policy name customizable

---

aws/eks-cluster/CHANGELOG.md
aws/eks-cluster/README.md
aws/eks-cluster/efs.tf
aws/eks-cluster/modules/efs/README.md
aws/eks-cluster/modules/efs/efs.tf
aws/eks-cluster/modules/efs/variables.tf
aws/eks-cluster/variables.tf

add variable to overwrite filesystem name

aws/eks_cluster: add variable to overwrite filesystem name

---

aws/openvpn/CHANGELOG.md
aws/openvpn/README.md
aws/openvpn/instance.tf
aws/openvpn/locals.tf
aws/openvpn/outputs.tf
aws/openvpn/scripts/install_openvpn.sh
aws/openvpn/sg.tf
aws/openvpn/tls.tf
aws/openvpn/variables.tf

* Allow using this module to use various available OAuth2 provider by adding variables: `oauth2_provider`, `oauth2_issuer`
* Allow validate group and role of the authorized identity via `oauth2_validate_groups` and `oauth2_validate_roles`
* Make management ssh key optional `create_management_key_pair`
* And add some variables for migrations: `custom_cert_dns_names`, `create_egress_vpn_rule`, `init_script_callback_comment`

aws/openvpn: add variables and features to module

---

aws/static-website/CHANGELOG.md
aws/static-website/README.md
aws/static-website/cloudfront.tf
aws/static-website/examples/complete/main.tf
aws/static-website/modules/cloudfront/README.md
aws/static-website/modules/cloudfront/main.tf
aws/static-website/modules/cloudfront/routing.tf
aws/static-website/modules/cloudfront/variables.tf
aws/static-website/s3.tf
aws/static-website/variables.tf

* Add a flag to enable www domain: `use_www_domain`
* Add `cloudfront_distribution_aliases` variable to custom distribution aliases
* Add `existing_s3_bucket_name` variable to specify the name of custom s3 bucket to use

aws/static-website: add custom variables

---

CHANGELOG.md

* AWS Static Website: [(./aws/static-website)](./aws/static-website/)
* Add a flag to enable www domain: `use_www_domain`
* Add `cloudfront_distribution_aliases` variable to custom distribution aliases
* Add `existing_s3_bucket_name` variable to specify the name of custom s3 bucket to use
* AWS OpenVPN: [(./aws/openvpn)](./aws/openvpn/)
* Allow using this module to use various available OAuth2 provider by adding variables: `oauth2_provider`, `oauth2_issuer`
* Allow validate group and role of the authorized identity via `oauth2_validate_groups` and `oauth2_validate_roles`
* Make management ssh key optional `create_management_key_pair`
* And add some variables for migrations: `custom_cert_dns_names`, `create_egress_vpn_rule`, `init_script_callback_comment`
* AWS SQS: …

Release v0.1.28

---

aws/vpc-endpoints/CHANGELOG.md
aws/vpc-endpoints/README.md

- Updated the changelog and README to reflect support for configuring EKS-related VPC endpoints in version 0.1.29. 
- This ensures accurate documentation and module usage.

Add VPC endpoint missing version

---

aws/vpc/CHANGELOG.md
aws/vpc/README.md
aws/vpc/main.tf
aws/vpc/variables.tf

Add private db subnet groups in vpc modules for migration

aws/vpc: add private db subnet groups

---

CHANGELOG.md

* AWS VPC: Add private database subnet groups [(./aws/vpc)](./aws/vpc/)
* AWS VPC Endpoints: * Add support for EKS VPC endpoint configuration [(./aws/vpc-endpoints)](./aws/vpc-endpoints/)
* AWS Security Group: Add variable `custom_sg_allow_all_within_vpc_egress_ipv6_cidr_blocks` to avoid update sg during migration [(./aws/security-group)](./aws/security-group/)

release: v0.1.29

---

qdrant/CHANGELOG.md
qdrant/README.md
qdrant/examples/README.md
qdrant/examples/main.tf
qdrant/main.tf
qdrant/outputs.tf
qdrant/variables.tf
qdrant/versions.tf

Init centralized Terraform module for qdrant vector database with all the code.

Init centralized Terraform module for qdrant vector database

---

aws/openvpn/CHANGELOG.md
aws/openvpn/README.md
aws/openvpn/instance.tf
aws/openvpn/variables.tf

remove user_data from ignore changes
bug: update variables in module OpenVPN doesn't trigger resource updates
ex: https://github.com/bridgehealth-ai/infra-terraform/pull/103 result in no changes
This is because updating user_data without recreating the instance is generally not expected behavior. User-data is executed only during the initial instance startup, so subsequent updates to user_data should typically trigger a new instance creation.
We can't make an optional lifecycle with a condition because it requires a static list.

aws/openvpn: remove user_data from ignore changes

---

CHANGELOG.md
aws/openvpn/CHANGELOG.md
qdrant/CHANGELOG.md

* AWS OpenVPN: [(./aws/openvpn/)](./aws/openvpn/)
* Add a flag to determine whenever to recreate OpenVPN instance when there is update in some variables: `replace_instance_on_update`.
* AWS Security Group: [(./aws/security-group/)](./aws/security-group/)
* Update Security Group Resources to Support Dynamic Ingress and Egress Rule Management
* Qdrant: [(./qdrant)](./qdrant)
* Initial commit with all the code

Release v0.1.30

---

aws/eks-helm/jenkins/CHANGELOG.md
aws/eks-helm/jenkins/README.md
aws/eks-helm/jenkins/efs-volume.tf
aws/eks-helm/jenkins/examples/README.md
aws/eks-helm/jenkins/examples/main.tf
aws/eks-helm/jenkins/locals.tf
aws/eks-helm/jenkins/main.tf
aws/eks-helm/jenkins/variables.tf
aws/eks-helm/jenkins/versions.tf

Add a new module to configure Jenkins on AWS Kubernetes via helm

Add AWS/EKS-Helm Jenkins module

---

datadog/aws-monitor/CHANGELOG.md
datadog/aws-monitor/README.md
datadog/aws-monitor/billing_monitor.tf
datadog/aws-monitor/elasticache.tf
datadog/aws-monitor/examples/README.md
datadog/aws-monitor/examples/main.tf
datadog/aws-monitor/locals.tf
datadog/aws-monitor/rds.tf
datadog/aws-monitor/variables.tf
datadog/aws-monitor/versions.tf
datadog/monitors/CHANGELOG.md
datadog/monitors/README.md
datadog/monitors/examples/README.md
datadog/monitors/examples/main.tf
datadog/monitors/main.tf
datadog/monitors/variables.tf
datadog/monitors/versions.tf

Add a base module `monitors` to create custom datadog monitors.
Add an `aws-monitor` module with common sets of datadog monitors for aws.

datadog: add datadog monitors modules

---

CHANGELOG.md

* AWS Helm / Jenkins: [(./aws/eks-helm/jenkins)](./aws/eks-helm/jenkins)
* Init module with all the code
* Datadog / Monitors: [(./datadog/monitors)](./datadog/monitors)
* Init module with all the code
* Datadog / AWS-Monitors: [(./datadog/aws-monitors)](./datadog/aws-monitors)
* Init module with all the code
* AWS OpenVPN: [(./aws/openvpn/)](./aws/openvpn/)
* Add missing a new line in the init script template

release v0.1.31

---

datadog/aws-monitor/billing_monitor.tf
datadog/aws-monitor/elasticache.tf
datadog/aws-monitor/rds.tf

Datadog  / AWS Monitor: add a default value for try expressions

datadog/aws-monitor: fix try expressions

---

CHANGELOG.md
datadog/aws-monitor/CHANGELOG.md

* Datadog / AWS-Monitors: [(./datadog/aws-monitors)](./datadog/aws-monitors)
* Add a default value for Terraform try functions

Release v0.1.32

---

CHANGELOG.md
aws/cloudwatch/alarm/CHANGELOG.md
aws/openvpn/CHANGELOG.md

* Cloudwatch Alarm [(./aws/cloudwatch/alarm)](./aws/cloudwatch/alarm)
* Ensure InstanceId is included when the namespace is "AWS/EC2".
* OpenVPN [(./aws/openvpn)](./aws/openvpn)
* Add outputs for EC2 instance.
* Introduced `http_tokens` and `http_endpoint` variables to control instance metadata service settings.
* Security Groups [(./aws/security-group)](./aws/security-group)
* Updated the logic to set from_port and to_port to -1 when the IP protocol is "-1", ensuring compatibility for security group rules with all protocols.
Terraform Plan 
N/A

Release v0.1.33

---

aws/oidc/jenkins-oidc/CHANGELOG.md
aws/oidc/jenkins-oidc/README.md
aws/oidc/jenkins-oidc/iam.tf
aws/oidc/jenkins-oidc/locals.tf
aws/oidc/jenkins-oidc/variables.tf

* Add provider `custom_oidc_policy_statement` to customize oidc policy statement.
* Add `var.oidc_policy_name` and `var.oidc_policy_description` to overwrite the existed default name and description

aws/jenkins_oidc: add variables to overwrite the default one

---

CHANGELOG.md

* AWS Jenkins OIDC: [(./aws/oidc/jenkins-oidc)](./aws/oidc/jenkins-oidc/)
* Add provider `custom_oidc_policy_statement` to customize oidc policy statement.
* Add `var.oidc_policy_name` and `var.oidc_policy_description` to overwrite the existed default name and description
* AWS Jenkins: [(./aws/eks-helm/jenkins)](./aws/eks-helm/jenkins)
* Add variable `jenkins_config_map_name` to use configMapRef in containerEnvFrom
* Add variable `jenkins_viewer` to add permission for GitHub team groups that defined in jenkins viewer

release: v0.1.34

---

aws/eks-helm/jenkins/CHANGELOG.md
aws/eks-helm/jenkins/README.md
aws/eks-helm/jenkins/examples/main.tf
aws/eks-helm/jenkins/main.tf
aws/eks-helm/jenkins/variables.tf

Update the Jenkins `gitHubPluginConfig` to match the variable `github_org_display_name`

correct: Jenkins module typo

---

aws/eks-cluster/CHANGELOG.md
aws/eks-cluster/README.md
aws/eks-cluster/modules/cloudwatch-logging/README.md
aws/eks-cluster/modules/cloudwatch-logging/versions.tf
aws/eks-cluster/modules/datadog-rbac/README.md
aws/eks-cluster/modules/datadog-rbac/versions.tf
aws/eks-cluster/modules/efs/README.md
aws/eks-cluster/modules/efs/versions.tf
aws/eks-cluster/modules/fargate-profile/README.md
aws/eks-cluster/versions.tf

* Update provider URLs (remove `registry.terraform.io`) for OpenTofu to map to their registry.

aws/eks-cluster: update provider URLs

---

CHANGELOG.md

* All modules: add an `override.tofu` file to override terraform version constraint to opentofu version constraint
* AWS eks-cluster: [(./aws/eks-cluster)](./aws/eks-cluster/)
* Update provider urls (remove `registry.terraform.io`) in order for OpenTofu to map to their registry.

Release v0.1.35

---

aws/s3/CHANGELOG.md
aws/s3/README.md
aws/s3/iam.tf
aws/s3/variables.tf

Add custom variables to overwrite default for migration

aws/s3: update variables to overwrite default

---

CHANGELOG.md

* Datadog aws-monitor: [(./datadog/aws-monitor)](./datadog/aws-monitor/)
* Remove unused variables `dd_users`.
* Datadog monitors: [(./datadog/monitors)](./datadog/monitors/)
* Add monitor_thresholds.ok and customize query type.
* Datadog mono-monitor: Init module [(./datadog/mono-monitor)](./datadog/mono-monitor/)
* Datadog service-monitor: Init module [(./datadog/service-monitor)](./datadog/service-monitor/)
* AWS S3: Add variables to overwrite policy name: `custom_readonly_policy_name`, `custom_read_write_policy_name` [(./aws/s3)](./aws/s3/)

release v0.1.36

---

aws/sqs/CHANGELOG.md
aws/sqs/README.md
aws/sqs/iam.tf
aws/sqs/main.tf
aws/sqs/outputs.tf
aws/sqs/variables.tf

* Add variable `enabled_dead_letter_queue` to optionally disable dlq
* Add variable `enabled_read_write_policy` and `read_write_policy_name` to optionally configure a read-write policy

aws/sqs: add a new optional read-write policy and make dlq optional

---

aws/static-website/CHANGELOG.md
aws/static-website/modules/cloudfront/override.tofu

* Add `override.tofu` to override Terraform version constrain with OpenTofu

aws/static-website/cloudfront: add override.tofu

---

CHANGELOG.md

* AWS SQS: [(./aws/sqs)](./aws/sqs)
* Add variable `enabled_dead_letter_queue` to optionally disable dlq
* Add variable `enabled_read_write_policy` and `read_write_policy_name` to optionally configure a read-write policy
* AWS StaticWebsite/Cloudfront: [(./aws/static-website/modules/cloudfront/)](./aws/static-website/modules/cloudfront/)
* Add `override.tofu` to override Terraform version constrain with OpenTofu
* AWS OIDC/Jenkins: [(./aws/oidc/jenkins-oidc)](./aws/oidc/jenkins-oidc/)
* Fix `for_each argument must be a map, or set of strings`: wrap the argument in `toset`

Release v0.1.37

---

aws/eks-helm/jenkins/CHANGELOG.md
aws/eks-helm/jenkins/override.tofu
aws/eks-helm/jenkins/variables.tf

* Remove variable validation with ref to other var since this feature hasn't been supported in OpenTofu
References in Variable Validation is not yet supported in OpenTofu
We need to wait for v1.9.0 to release https://github.com/opentofu/opentofu/pull/2216

aws/eks-helm/jenkins: Remove variable validation with ref to support OpenTofu

---

CHANGELOG.md

* Datadog aws-monitor: [(./datadog/aws-monitor)](./datadog/aws-monitor/)
* Update `renotify_occurrences` for each default services
* Datadog monitors: [(./datadog/monitors)](./datadog/monitors/)
* Add monitor_threshold `warning` and `warning_recovery`.
* AWS Neo4j module: [(./aws/eks-helm/neo4j)](./aws/eks-helm/neo4j)
* Add Neo4j helm deployment module

release: v0.1.38

---

aws/oidc/provider/CHANGELOG.md
aws/oidc/provider/main.tf
aws/oidc/provider/outputs.tf

Update `var.create_provider` for `aws_iam_openid_connect_provider` to prevent bugs from not found

aws/oidc: add a flag to prevent bugs from not found data

---

aws/oidc/provider/main.tf
aws/ses/CHANGELOG.md
aws/ses/README.md
aws/ses/dkim-record.tf
aws/ses/mx-record.tf
aws/ses/variables.tf

AWS SES: add dkim and mx records.
https://www.notion.so/Infra-Rollout-centralized-Terraform-modules-to-Sky-16901fb05bf180e592d3dc1b3ea10b20?pvs=4

AWS SES: add dkim and mx records

---

CHANGELOG.md

* AWS SES:  [(./aws/ses)](./aws/ses)
* Add DKIM records and MX records options.
* AWS OIDC Provider: [(./aws/oidc/provider)](./aws/oidc/provider)
* Update `var.create_provider` for `aws_iam_openid_connect_provider` to prevent bugs from not found

release: v0.1.39

---

aws/oidc/provider/CHANGELOG.md
aws/oidc/provider/main.tf

* Remove create `var.create_provider` from `tls_certificate` to prevent bugs.

aws/jenkins-oidc: fix oidc provider bug

---

CHANGELOG.md

* AWS MWAA: [(./aws/mwaa)](./aws/mwaa)
* Add AWS MWAA Terraform module
* AWS OIDC Provider: [(./aws/oidc/provider)](./aws/oidc/provider)
* Remove create `var.create_provider` from `tls_certificate` to prevent bugs.

release: v0.1.40

---

aws/static-website/CHANGELOG.md
aws/static-website/README.md
aws/static-website/modules/cloudfront/main.tf
aws/static-website/s3.tf
aws/static-website/variables.tf

* Add `bucket_prefix`, `s3_custom_readonly_policy_name`, `s3_custom_read_write_policy_name`, `s3_readonly_policy_description`, `s3_read_write_policy_description` to avoid resource recreation.

Update AWS static website: add custom options to avoid recreation

---

CHANGELOG.md

release v0.1.41
* AWS static-website: Add `bucket_prefix`, `s3_custom_readonly_policy_name`, `s3_custom_read_write_policy_name`, `s3_readonly_policy_description`, `s3_read_write_policy_description` to avoid resource recreation. [(./aws/static-website)](./aws/static-website)

release v0.1.41

---

CHANGELOG.md
aws/eks-helm/aws-load-balancer-controller/CHANGELOG.md

* AWS Eks-Helm/ALB-Controller [(./aws/eks-helm/aws-load-balancer-controller/)](./aws/eks-helm/aws-load-balancer-controller/)
* Add new policy documents and auto map associated policy based on chart_version.
https://www.notion.so/BUG-Infra-Fix-the-CI-CD-flow-175642cd4ca780c78bc7e312a4eb8dad

release v0.1.42

---

aws/elasticache/CHANGELOG.md
aws/elasticache/README.md
aws/elasticache/main.tf
aws/elasticache/outputs.tf
aws/elasticache/variables.tf
aws/elasticache/versions.tf

* Add output `elasticache_replication_group_configuration_endpoint_address` and variable `transit_encryption_enabled`.

Update AWS elasticache

---

CHANGELOG.md

* AWS elasticache: Add output `elasticache_replication_group_configuration_endpoint_address` and variable `transit_encryption_enabled`. [(./aws/elasticache)](./aws/elasticache)

release: v0.1.43

---

CHANGELOG.md

release: v0.1.44

---

aws/sqs/CHANGELOG.md
aws/sqs/README.md
aws/sqs/iam.tf
aws/sqs/main.tf
aws/sqs/variables.tf

* Change `max_receive_count` type to number.
* Separate `aws_sqs_queue.queue.redrive_policy` to `aws_sqs_queue_redrive_policy.this`.
* Add attribute `redrive_allow_policy` to `aws_sqs_queue.dlq`.

Update AWS SQS: add dlq allow redrive policy

---

CHANGELOG.md

* AWS SQS: [(./aws/sqs)](./aws/sqs)
* Change `max_receive_count` type to number.
* Separate `aws_sqs_queue.queue.redrive_policy` to `aws_sqs_queue_redrive_policy.this`.
* Add attribute `redrive_allow_policy` to `aws_sqs_queue.dlq`.

release: v0.1.45

---

CHANGELOG.md

* AWS SES: [(./aws/ses)](./aws/ses)
* Add variable enabled_ses_identity_policy to make ses_identity_policy optional
https://www.notion.so/c0x12c/Infra-Rollout-centralized-Terraform-modules-to-ResiQuant-17601fb05bf180a09c05f106bf4468d9

Release v0.1.46

---

aws/static-website/CHANGELOG.md
aws/static-website/README.md
aws/static-website/cloudfront.tf
aws/static-website/examples/complete/main.tf
aws/static-website/modules/cloudfront/README.md
aws/static-website/modules/cloudfront/main.tf
aws/static-website/modules/cloudfront/variables.tf
aws/static-website/variables.tf

Add `ordered_cache_behaviors` to custom `aws_cloudfront_distribution.ordered_cache_behavior`.

Add ordered_cache_behaviors to AWS static-website module

---

CHANGELOG.md

* AWS static-website: Add `ordered_cache_behaviors` to custom `aws_cloudfront_distribution.ordered_cache_behavior`. [(./aws/static-website)](./aws/static-website)

release: v0.1.47

---

CHANGELOG.md

* AWS Opensearch: [(./aws/opensearch)](./aws/opensearch/)
* Add option to create service link role via variable `create_linked_role`
https://www.notion.so/c0x12c/Infra-Rollout-centralized-Terraform-modules-to-ResiQuant-17601fb05bf180a09c05f106bf4468d9

Release v0.1.48

---

CHANGELOG.md

* AWS Vanta: [(./aws/vanta)](./aws/vanta/)
* Add IAM role and IAM policy for Vanta Auditor
* AWS Neo4j: [(./aws/eks-helm/neo4j)](./aws/eks-helm/neo4j)
* Set Neo4j auth secret and update ingress HTTP port
Terraform plan

Release: v0.1.49

---

aws/vanta/CHANGELOG.md
aws/vanta/README.md
aws/vanta/data.tf
aws/vanta/examples/complete/main.tf
aws/vanta/variables.tf

AWS Vanta:
* Make vanta External Scanner ID customizable via `vanta_scanner_external_id`
Need to customize this ID per AWS account.
SOC2 BridgehealthAI

aws/vanta: add variable for vantar external scanner id

---

CHANGELOG.md

* AWS Vanta: [(./aws/vanta)](./aws/vanta/)
* Make vanta External Scanner ID customizable via `vanta_scanner_external_id`
SOC2

Release v0.1.50

---

aws/openvpn/CHANGELOG.md
aws/openvpn/README.md
aws/openvpn/instance.tf
aws/openvpn/sg.tf
aws/openvpn/variables.tf

* Add optional existing public key value `ec2_public_key` and custom key name `key_name`.
* Add security group to allow ssh access to vpn `default_ssh_vpn`.
* Remove resource tag.

update aws/openvpn key name and security group

---

CHANGELOG.md

* AWS OpenVPN: [(./aws/openvpn)](./aws/openvpn/)
* Add optional existing public key value `ec2_public_key` and custom key name `key_name`.
* Add security group to allow ssh access to vpn `default_ssh_vpn`.
* Remove resource tag.

release: v0.1.51

---

aws/mwaa/CHANGELOG.md
aws/mwaa/main.tf

- This change improves log visibility and aligns with standard logging practices for better debugging and monitoring.
- Updated the default log level for MWAA task logs from WARNING to INFO. 
Terraform Plan
N/A

Set MWAA task log level to INFO by default.

---

CHANGELOG.md

Rollout infra new version: v0.1.52
* AWS password policy: [(./aws/password-policy)](./aws/password-policy/)
* Configures an IAM account password policy in AWS 
* Enforcing security requirements such as minimum password length, required character types, and user password management capabilities.
* AWS MWAA: [(./aws/mwaa)](./aws/mwaa)
* Set MWAA task log level to INFO by default.
Terraform Plan
N/A

Release: v0.1.52

---

aws/ses/CHANGELOG.md
aws/ses/main.tf

Fix the case we needn't verify the domain, but we need to publish MX or DKIM record
https://www.notion.so/c0x12c/Terraform-Terraform-Modules-17901fb05bf180bda02bef71ebbed9f3?pvs=4

bug: handle data aws route53 zone

---

aws/eks-helm/aws-load-balancer-controller/README.md

eks-helm/alb: add missing example in readme

---

aws/amplify/examples/nextjs-app/outputs.tf
aws/elasticache/examples/complete/main.tf
aws/guardduty/examples/complete/main.tf
aws/mwaa/CHANGELOG.md
aws/mwaa/README.md
aws/password-policy/CHANGELOG.md
aws/password-policy/README.md
aws/schedulers/examples/complete/main.tf
aws/sqs/examples/complete/main.tf

Removed unused variables and attributes in AWS example Terraform modules for simplicity and clarity. 
Updated module references and changelog versions to ensure consistency across documentation.
Terraform Plan

Refactor and clean up aws terraform examples and changelogs

---

CHANGELOG.md

* Fix `auth_token` is enabled if `transit_encryption_enabled` is true
N/A

release_0.1.54

---

aws/eks-cluster/CHANGELOG.md
aws/eks-cluster/README.md
aws/eks-cluster/addons.tf
aws/eks-cluster/variables.tf

* Add variables `addons_vpc_cni_version`, `addons_kube_proxy_version`, `addons_coredns_version` to specify the version of addons.

aws/eks-cluster: make eks addons versions configurable

---

CHANGELOG.md

Features:
* AWS S3: [(./aws/s3)](./aws/s3)
* Add variable `enabled_access_logging` and `access_log_target_bucket_id` to optionally configure access logging for the bucket.
* AWS EKS-Cluster [(./aws/eks-cluster/)](./aws/eks-cluster/)
* Add variables `addons_vpc_cni_version`, `addons_kube_proxy_version`, `addons_coredns_version` to specify the version of addons.

Release v0.1.55

---

aws/postgres/CHANGELOG.md
aws/postgres/README.md
aws/postgres/db_instance/main.tf
aws/postgres/db_instance/variables.tf
aws/postgres/main.tf
aws/postgres/variables.tf

* Add optional variable `snapshot_identifier` to specify whether or not to create the database instance from a snapshot.
Need when we need to restore the database instance from a snapshot
https://www.notion.so/IaaS-Test-recovery-RDS-instance-from-backup-snapshots-17a5218ab94f809ca0cbd8e48ef0a765

aws/postgres: add option to create the database instance from snapshot

---

gcp/service-config/CHANGELOG.md
gcp/service-config/README.md
gcp/service-config/examples/complete/main.tf
gcp/service-config/service-account.tf
gcp/service-config/variables.tf

Fix GCP Service Config module validation failure due to unused variable `project_id` reference.
Remove `project_id`.
1. Check PR validation.

fix: GCP Service Config module validation

---

CHANGELOG.md

* AWS Postgres [(./aws/postgres/)](./aws/postgres/)
* Add optional variable `snapshot_identifier` to specify whether or not to create database instance from a snapshot.
* AWS S3 [(./aws/s3/)](./aws/s3/)
* Add a submodule `access-log-policy` to configure bucket policy to allow AWS services to write access logs from other services/buckets.
* GPC ServiceConfig [(./gcp/service-config/)](./gcp/service-config/)
* Fixed a bug where the variable `project_id` is redundant and vulnerable.

Release v0.1.56

---

aws/s3/CHANGELOG.md
aws/s3/README.md
aws/s3/access-log-policy/README.md
aws/s3/access-log-policy/examples/main.tf
aws/s3/access-log-policy/main.tf
aws/s3/access-log-policy/variables.tf
aws/s3/main.tf

AWS/S3:
* Correct access-log-policy resource (use bucket arn instead of id)

[Fix] aws/s3: correct access log policy resource

---

aws/ecr/CHANGELOG.md
aws/ecr/README.md
aws/ecr/main.tf
aws/ecr/variables.tf

* Add variables `custom_ecr_scanning`, `scan_type`, `scan_frequency` to configure ecr scanning.

[Feat] aws/ecr: custom ecr scanning

---

CHANGELOG.md

* AWS ECR [(./aws/ecr/)](./aws/ecr/)
* Add variables `custom_ecr_scanning`, `scan_type`, `scan_frequency` to configure ecr scanning.
* AWS S3 [(./aws/s3/)](./aws/s3/)
* Correct access-log-policy resource (use bucket arn instead of id)

Release v0.1.57

---

aws/eks-helm/datadog/CHANGELOG.md
aws/eks-helm/datadog/README.md
aws/eks-helm/datadog/examples/main.tf
aws/eks-helm/jenkins/CHANGELOG.md
aws/eks-helm/jenkins/README.md
aws/eks-helm/jenkins/examples/main.tf
aws/eks-helm/metrics-server/CHANGELOG.md
aws/eks-helm/metrics-server/README.md

- Updated README files to include usage details for installing and configuring EKS Helm modules (Jenkins, Datadog, and Metrics Server). 
Terraform Plan 
N/A

Add usage examples for helm modules: jenkins, datadog, metrics server

---

CHANGELOG.md

* Enable aws billing alarm: [(./aws/cloudwatch/alarm/)](./aws/cloudwatch/alarm/)
* Add usage examples for helm modules:
* [(./aws/eks-helm/jenkins/)](./aws/eks-helm/jenkins/)
* [(./aws/eks-helm/datadog/)](./aws/eks-helm/datadog/)
* [(./aws/eks-helm/metrics-server/)](./aws/eks-helm/metrics-server/)
* Add variables for eks api endpoint access control [(./aws/eks-cluster/)](./aws/eks-cluster/)
* Add Terraform module for GitHub Actions self-hosted
runner [(./aws/github-self-hosted-runners/)](./aws/github-self-hosted-runners/)
* Add new variables for Datadog module to enable/disable some flags [(./aws/eks-helm/datadog/)](./aws/eks-helm/datadog/)
* Add Terraform module for Keda [(./aws/eks-helm/keda/)](./aws/eks-helm/keda/)
N/A

release: 0.1.59

---

aws/eks-helm/keda/README.md
aws/eks-helm/keda/assume-role-policy/CHANGELOG.md
aws/eks-helm/keda/assume-role-policy/README.md
aws/eks-helm/keda/assume-role-policy/examples/complete/README.md
aws/eks-helm/keda/assume-role-policy/examples/complete/main.tf
aws/eks-helm/keda/assume-role-policy/main.tf
aws/eks-helm/keda/assume-role-policy/override.tofu
aws/eks-helm/keda/assume-role-policy/variables.tf
aws/eks-helm/keda/assume-role-policy/versions.tf
aws/eks-helm/keda/examples/complete/main.tf
aws/eks-helm/keda/iam.tf
aws/eks-helm/keda/outputs.tf
aws/eks-helm/keda/variables.tf

To reduce the circle dependencies (update the assume role for keda-operator and pod-role), we decided to separate the KEDA helm install and KEDA Attach the assume role policy
https://www.notion.so/c0x12c/Datum-Autoscaling-with-workers-for-resource-extensive-tasks-16f01fb05bf1807e9b23c503bf4bfae0?pvs=4

feat: separate the keda helm and ke-operator-assume-role-policy

---

aws/github-self-hosted-runners/CHANGELOG.md
aws/github-self-hosted-runners/README.md
aws/github-self-hosted-runners/main.tf
aws/github-self-hosted-runners/variables.tf

- Add variable `update_default_launch_template_version` to allowed update the default launch template version automatically (default = true)

aws/github-self-hosted-runner: update launch template default version automatically

---

CHANGELOG.md

* AWS / GitHub Self-hosted Runner: [(./aws/github-self-hosted-runners/)](./aws/github-self-hosted-runners/)
* Add variable `update_default_launch_template_version` to allowed update the default launch template version automatically (default = true)
*  Rename variable `vpc_zone_identifier` to `subnet_ids`

Release v0.1.61

---

CHANGELOG.md

* AWS OpenVPN: [(./aws/openvpn/)](./aws/openvpn/)
* Make ssh rule in security group optional and disable by default, var: `allow_remote_ssh_access`
* AWS Cloudwatch/Alarm: [(./aws/cloudwatch/alarm/)](./aws/cloudwatch/alarm/)
* Extended CloudWatch alarm configuration to support EC2 AutoScalingGroup
* AWS OpenVPN: [(./aws/openvpn/)](./aws/openvpn/)
* Correct instance id and instance arn output

Release v0.1.62

---

CHANGELOG.md

* AWS ECS Application: [(./aws/ecs-application/)](./aws/ecs-application/)
* Refactor and remove Datadog configuration
* AWS ALB: [(./aws/alb/)](./aws/alb/)
* Remove unused target group
*
N/A

release: 0.1.63

---

aws/static-website/CHANGELOG.md
aws/static-website/README.md
aws/static-website/cloudfront.tf
aws/static-website/examples/complete/README.md
aws/static-website/examples/complete/main.tf
aws/static-website/modules/cloudfront/README.md
aws/static-website/modules/cloudfront/locals.tf
aws/static-website/modules/cloudfront/main.tf
aws/static-website/modules/cloudfront/routing.tf
aws/static-website/modules/cloudfront/variables.tf
aws/static-website/variables.tf

Handle create the Static website for Root domain
N/A

feat: update static website to support root domain

---

CHANGELOG.md
aws/static-website/README.md

* AWS Static website: [(./aws/static-website/)](./aws/static-website/)
* Allow to creation the website with the root domain
N/A

release: 0.1.64

---

CHANGELOG.md

* AWS EKS Cluster: [(./aws/eks-cluster/)](./aws/eks-cluster/)
* Add EKS access entries and API/config map authentication options
* AWS EKS Access Entry: [(./aws/eks-access-entry/)](./aws/eks-access-entry/)
* Init EKS access entries module
* AWS GitHub Self-hosted Runner: [(./aws/github-self-hosted-runners/)](./aws/github-self-hosted-runners/)
* Updated configurations to utilize the new custom AMI for launch templates.
Terraform Plan
N/A

Release v0.1.65

---

aws/static-website/README.md
aws/static-website/cloudfront.tf
aws/static-website/modules/cloudfront/README.md
aws/static-website/modules/cloudfront/locals.tf
aws/static-website/modules/cloudfront/main.tf
aws/static-website/modules/cloudfront/variables.tf
aws/static-website/variables.tf

[BridgehealthAI Penetration Test Report 20250128 (1) (1).pdf](https://github.com/user-attachments/files/18729698/BridgehealthAI.Penetration.Test.Report.20250128.1.1.pdf)
Resolve some low risk from the report (missing headers in response)
Add boolen value to check if we need enable response headers policy configuration or not
https://www.notion.so/SOC2-Add-some-response-header-to-CloudFront-1964e7d27157808ab5eacc67e43ef0e7

Add response header configuration option for cloud front

---

CHANGELOG.md
aws/static-website/CHANGELOG.md

* AWS EKS Access Entry: [(./aws/eks-access-entry/)](./aws/eks-access-entry/)
* Updated resources dependency for improved performance
* Added functionality to skip role creation if the role already exists
* AWS EKS Cluster: [(./aws/eks-cluster/)](./aws/eks-cluster/)
* Enable or disable access mode dynamically in the access_config of the EKS cluster resource
* AWS GitHub Self-hosted Runner: [(./aws/github-self-hosted-runners/)](./aws/github-self-hosted-runners/)
* Update Terraform installation to allow version suffix support
* AWS Static Website: [(./aws/static-website/)](./aws/static-website/)
* Add response header configuration option for cloud front
Terraform Plan
N/A

Release v0.1.66

---

CHANGELOG.md

* AWS S3: [(./aws/s3/)](./aws/s3/)
* Add `read_write_actions` which allow s3 policy can be added permissions base on requirement of projects
* AWS EKS: Helm Jenkins [(./aws/eks-helm/jenkins)](./aws/eks-helm/jenkins)
* Create the credential using github_app_credential_id instead of gihub_credential_id
* Remove unused input `gihub_credential_id`

Release: v0.1.68

---

aws/oidc/github-oidc/CHANGELOG.md
aws/oidc/jenkins-oidc/CHANGELOG.md
aws/oidc/provider/CHANGELOG.md
aws/oidc/provider/main.tf

Fix OIDC resource `aws_iam_openid_connect_provider` creation error.
> The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created.
Replace `try` with `length`.
1. Check plan
Tested on local.

fix: OIDC resource `aws_iam_openid_connect_provider` creation error

---

CHANGELOG.md

* AWS oidc sub module provider: [(./aws/oidc/provider)](./aws/oidc/provider)
* Fix `aws_iam_openid_connect_provider` resource creation using `length` instead of `try` to resolve error
that `data source is evaluated only at apply time`.

release: v0.1.70

---

aws/eks-service/CHANGELOG.md
aws/eks-service/README.md
aws/eks-service/main.tf

- Corrected the variable used for the EKS service account namespace in the IAM policy. 
- Structure: `"system:serviceaccount:<namespace>:<serviceaccount-name>"`
Terraform Plan

Fix EKS service account namespace reference

---

CHANGELOG.md

* AWS EKS Service: [(./aws/eks-service)](./aws/eks-service)
* Fix EKS service account namespace reference
Terraform Plan

Release: v0.1.71

---

CHANGELOG.md

* AWS EKS Service: [(./aws/eks-service)](./aws/eks-service)
* Add the flag to customize the service account for each service.

release: 0.1.73

---

CHANGELOG.md

Release v0.1.74

---

aws/eks-helm/neo4j/CHANGELOG.md
aws/eks-helm/neo4j/README.md
aws/eks-helm/neo4j/main.tf
aws/eks-helm/neo4j/scripts/neo4j-config.conf
aws/eks-helm/neo4j/variables.tf
aws/eks-helm/neo4j/versions.tf
aws/wafv2/CHANGELOG.md

- Renamed and updated configuration management to use templates for Neo4j settings. 
- Added a new variable `neo4j_procedures` to define allowed procedures and functions.
- Updated documentation to reflect the changes.
Terraform Plan

Add support for specifying allowed Neo4j procedures

---

CHANGELOG.md

Bug fixes
* AWS EKS Cluster: [(./aws/eks-helm)](./aws/eks-helm)
* add the wafv2 arn acl config for load balancer

Release v0.1.75

---

CHANGELOG.md

* Add `service_accounts` variables to handle custom service accounts

Release v0.1.76

---

aws/ecs-application/CHANGELOG.md
aws/ecs-application/README.md
aws/ecs-application/efs.tf
aws/ecs-application/examples/complete/main.tf
aws/ecs-application/locals.tf
aws/ecs-application/main.tf
aws/ecs-application/variables.tf
aws/efs/CHANGELOG.md
aws/efs/README.md
aws/efs/data.tf
aws/efs/examples/complete/README.md
aws/efs/examples/complete/main.tf
aws/efs/examples/complete/outputs.tf
aws/efs/main.tf
aws/efs/outputs.tf
aws/efs/override.tofu
aws/efs/variables.tf
aws/efs/versions.tf

- Some ECS service need a persistent volume (such as Wordpress), so we add a configuration to integrate with AWS EFS to enable the persistent volume
N/A

feat: ecs-application add persistent_volume

---

CHANGELOG.md

* AWS ECS Application: [(./aws/ecs-application)](./aws/ecs-application)
* Add `persistent_volume` and integrate with EFS service
* Managed nodes: only add iam role policy when there is at least 1 statemenet
* Managed nodes: don't ignore desired_size

Release v0.1.78

---

CHANGELOG.md
aws/eks-cluster/CHANGELOG.md
aws/rds/CHANGELOG.md
datadog/aws-monitor/CHANGELOG.md

* AWS RDS: [(./aws/rds)](./aws/rds)
* Add variable `use_secret_manager` and `secret_manager_db_password_name` to create Secret Manager for database
password management.
* Add variable `password_length` to custom database password length.
* Add variable `db_subnet_group_name` for migration purpose.
* Add variable `additional_postgres_parameters` for additional parameters on PostgreSQL instance.
* AWS RDS: [(./aws/rds)](./aws/rds)
* Correct `copy_tags_to_snapshot` input to submodule `db_instance`.

release: v0.1.79

---

aws/sqs/CHANGELOG.md
aws/sqs/README.md
aws/sqs/main.tf
aws/sqs/variables.tf

Add `content_based_deduplication` attribute.

AWS SQS: add content_based_deduplication

---

CHANGELOG.md
aws/sqs/CHANGELOG.md
datadog/aws-monitor/CHANGELOG.md

* AWS SQS: [(./aws/sqs)](./aws/sqs)
* Add attribute `content_based_deduplication` to `aws_sqs_queue.queue`.
* Remove `elasticache_cache_errors` for elasticache monitor, which was not neccessary

release: v0.1.80

---

CHANGELOG.md

* Datadog Dashboard: [(./datadog/dashboard)](./datadog/dashboard)
* Init Datadog Dashboard module
* AWS SES: [(./aws/ses)](./aws/ses)
* Add the Lambda function to log the SES Outgoing Emails to the Datadog
* AWS EKS Cluster [(./aws/eks-cluster)](./aws/eks-cluster)
* Add support for the EFS CSI driver in EKS Managed Node Groups
Terraform Plan

Release v0.1.81

---

aws/ecs-application/CHANGELOG.md
aws/ecs-application/README.md
aws/ecs-application/alb.tf
aws/ecs-application/efs.tf
aws/ecs-application/iam.tf
aws/ecs-application/locals.tf
aws/ecs-application/main.tf
aws/ecs-application/outputs.tf
aws/ecs-application/route53.tf
aws/ecs-application/security_group.tf
aws/ecs-application/variables.tf
aws/sendgrid/CHANGELOG.md
aws/sendgrid/README.md

* Introduces new variables:
* `task_cpu` and `task_memory`: to define task resources, container resource defined
by `container_cpu`, `container_memory`.
* `cloudwatch_log_group_name`, `cloudwatch_log_group_migration_name`: to define cloudwatch log group name.
If `cloudwatch_log_group_migration_name` is not null, it will create a log group for service migration logs.
* `overwrite_task_role_name`, `overwrite_task_execution_role_name`, `task_policy_secrets_description`, `task_policy_ssm_description`:
fallback on default value.
* `enabled_datadog_sidecar`, `dd_site`, `dd_api_key_arn`, `dd_agent_image`, `dd_port`: supports datadog sidecar
definitions.
* `use_alb`: whether to use ALB.
- Add datadog sidecar definitions.
- Support custom naming and description for migration purpose.
- Extend …

add datadog definition to ecs-application

---

CHANGELOG.md
aws/ecs-application/README.md

* AWS ECS application: [(./aws/ecs-application)](./aws/ecs-application)
* Introduces new variables:
* `task_cpu` and `task_memory`: to define task resources, container resource defined
by `container_cpu`, `container_memory`.
* `cloudwatch_log_group_name`, `cloudwatch_log_group_migration_name`: to define cloudwatch log group name.
If `cloudwatch_log_group_migration_name` is not null, it will create a log group for service migration logs.
* `overwrite_task_role_name`, `overwrite_task_execution_role_name`, `task_policy_secrets_description`, `task_policy_ssm_description`:
fallback on default value.
* `enabled_datadog_sidecar`, `dd_site`, `dd_api_key_arn`, `dd_agent_image`, `dd_port`: supports datadog sidecar
definitions.
* `use_alb`: whether to use ALB.

release: v0.2.1

---

CHANGELOG.md

* AWS ECS: [(./aws/ecs-cluster)](./aws/ecs-cluster)
* Add ECS Service Connect using `enabled_service_connect`.
* AWS ECS application: [(./aws/ecs-application)](./aws/ecs-application)
* Add ECS Service Connect using `enabled_service_connect` and `service_connect_configuration`.

release: v0.2.2

---

CHANGELOG.md
aws/ecs-application/CHANGELOG.md
aws/ecs-application/security-group.tf

`ecs-application`: Allow VPC internal connection to container port if variable `enabled_service_connect` is set to true.
To allow internal service connect.
Update ecs service security group.
If `enabled_service_connect`, it add ingress rule to security group, that allow all connection within vpc to `container_port`.

update ecs-application: allow vpc internal connection to container port

---

CHANGELOG.md

* AWS EKS Service: [(./aws/eks-service)](./aws/eks-service)
* Add inline k8s service account annotations

release: 0.2.6

---

CHANGELOG.md

* AWS EKS Access Entry: [(./aws/eks-access-entry)](./aws/eks-access-entry)
* Use the inline EKS Access Entry
* Add the labels for managed_nodes
* AWS EKS Helm Keda [(./aws/eks-helm/keda)](./aws/eks-helm/keda)
* Add the labels and tolerations
* AWS EKS Helm Datadog [(./aws/eks-helm/datadog)](./aws/eks-helm/datadog)
* Add the labels and tolerations
* AWS EKS Helm Metrics Server [(./aws/eks-helm/metrics-server)](./aws/eks-helm/metrics-server)
* Add the labels and tolerations
* AWS EKS Helm Neo4j [(./aws/eks-helm/neo4j)](./aws/eks-helm/neo4j)
* Add the labels and tolerations

release: 0.3.0

---

aws/eks-helm/keycloak/CHANGELOG.md
aws/eks-helm/keycloak/README.md
aws/eks-helm/keycloak/examples/complete/README.md
aws/eks-helm/keycloak/examples/complete/main.tf
aws/eks-helm/keycloak/main.tf
aws/eks-helm/keycloak/outputs.tf
aws/eks-helm/keycloak/override.tofu
aws/eks-helm/keycloak/variables.tf
aws/eks-helm/keycloak/versions.tf

Init Keycloak eks helm module
N/A

feat: keycloak

---

CHANGELOG.md

* Init AWS EKS Helm ArgoCD [(./aws/eks-helm/argocd)](./aws/eks-helm/argocd)
https://www.notion.so/c0x12c/Implement-ArgoCD-module-1c201fb05bf18053a9effbd82bf3a7cc?pvs=4

release: 0.3.2

---

CHANGELOG.md

* AWS EKS Helm ArgoCD [(./aws/eks-helm/argocd)](./aws/eks-helm/argocd)
* Update provider version
* Split CRDs include `Projects` and `Applications` to a single sub-module, which will handle creating Projects and Applications.

release: v0.3.3

---

aws/elasticache/CHANGELOG.md
aws/elasticache/README.md
aws/elasticache/main.tf
aws/elasticache/variables.tf

AWS: Elasticache: add `at_rest_encryption_enabled`
To enable encryption at rest.
Add `at_rest_encryption_enabled`, default = `false`.

AWS: Elasticache: add `at_rest_encryption_enabled`

---

CHANGELOG.md

* AWS Elasticache [(./aws/elasticache)](./aws/elasticache)
* Add `at_rest_encryption_enabled`.

release: v0.3.4

---

CHANGELOG.md
aws/eks-helm/argocd/CHANGELOG.md
aws/eks-helm/argocd/main.tf

* AWS EKS Helm ArgoCD [(./aws/eks-helm/argocd)](./aws/eks-helm/argocd)
* Remove those attributes when creating helm argocd
```hcl
wait             = true
timeout          = 300
```

fix: remove wait and timeout

---

CHANGELOG.md

* AWS EKS Helm ArgoCD: [(./aws/eks-helm/argocd)](./aws/eks-helm/argocd)
* Update Ingress and OIDC Connection
* Add `issuer_url` for dex config
* Add `transit_encryption_mode` to `aws_elasticache_replication_group`.
* AWS Static Website: [(./aws/static-website)](./aws/static-website)
* Add `s3_redirect_domain` to configure addressed S3 bucket to redirect to another domain
* AWS OpenSearch: [(./aws/opensearch)](./aws/opensearch)
* Add `encrypt_at_rest_enabled` to enable encryption of data at rest.

release: v0.3.8

---

CHANGELOG.md

* Add some configuration to enable EFS CSI on ManagedNodeGroup
* nodeSelector
* tolerations
* AWS IRSA

release: 0.3.9

---

CHANGELOG.md

* Add `replicas_per_node_group` to support multi-az.

release: v0.3.10

---

CHANGELOG.md

* Add `nginx-ingress-controller` module

release: 0.3.11

---

CHANGELOG.md

* Add RDS namespace `identifier`.

release: v0.3.13

---

CHANGELOG.md

* AWS Helm Nginx Ingress Controller: [(./aws/eks-helm/nginx-ingress-controller)](./aws/eks-helm/nginx-ingress-controller)
* Update replicas variable name

release: 0.3.14

---

aws/eks-helm/argocd/CHANGELOG.md
aws/eks-helm/argocd/examples/main.tf
aws/eks-helm/argocd/locals.tf
aws/eks-helm/argocd/modules/argocd-project/main.tf
aws/eks-helm/argocd/modules/argocd-project/variables.tf
aws/eks-helm/argocd/variables.tf

* Add predefined group rules for projects.
* Update destinations for projects and root applications
* Update condition for adding in-cluster and rename it

feat: add predefined group and fix destinations

---

CHANGELOG.md

* AWS KMS: [(./aws/kms)](./aws/kms)
* Add statements to KMS policy via `additional_statements`.
* AWS Cloudtrail: [(./aws/cloudtrail)](./aws/cloudtrail)
* Restrict HTTP access to S3 bucket via `disabled_s3_http_access`.
* AWS s3: [(./aws/s3)](./aws/s3)
* Restrict HTTP access to S3 bucket via `disabled_s3_http_access`.
* AWS EKS Helm ArgoCD: [(./aws/eks-helm/argocd)](./aws/eks-helm/argocd)
* Add predefined group rules for projects.
* Update destinations for projects and root applications
* Update condition for adding in-cluster and rename it

release: v0.3.15

---

aws/opensearch/CHANGELOG.md
aws/opensearch/README.md
aws/opensearch/main.tf
aws/opensearch/variables.tf

Add config for multi-az.
Add variables: `availability_zone_count` and `zone_awareness_enabled`.
`zone_awareness_enabled` is default to false. Set to true to enable multi-az deployment.
`availability_zone_count` is required to be 2-3 AZs for multi-az deployment.
Once these 2 variables are set, `instance_count` must be >= `availability_zone_count`.
Replica is set to 1 automatically by AWS.
Verified.

Opensearch: add config for multi-AZ

---

CHANGELOG.md

* AWS Static website: [(./aws/static-website)](./aws/static-website)
* Add `use_wildcard_domain` to support add route53 wildcard to our cloudfront
* AWS OpenSearch: [(./aws/opensearch)](./aws/opensearch)
* Add `availability_zone_count` and `zone_awareness_enabled` to enable multi-az

release: 0.3.16

---

CHANGELOG.md

* AWS S3: [(./aws/s3)](./aws/s3)
* Add S3 lifecycle configuration `s3_lifecycle_rules`.

release: v0.3.17

---

CHANGELOG.md

* AWS S3: [(./aws/s3)](./aws/s3)
* Update `aws_s3_bucket_policy` with creation flag `create_bucket_policy`.

release: v0.3.18

---

CHANGELOG.md

* Add `custom_redis_parameters` to add the custom redis configuration.

release: 0.4.1

---

CHANGELOG.md

* AWS EKS Helm ArgoCD: [(./aws/eks-helm/argocd)](./aws/eks-helm/argocd)
* Change variables that defined in `camelCase` to `snake_case`
* `var.external_cluster`
* assumeRoles -> assume_role
* clusterResources -> cluster_resources
* awsAuthConfig -> aws_auth_config
* clusterName -> cluster_name
* roleARN -> role_arn
* tlsClientConfig -> tls_client_config
* caData -> ca_data
* Add variable `enabled_managed_in_cluster` to enable in_cluster management, and `in_cluster_name` to change its name when `enabled_managed_in_cluster` is enable

release: v0.4.2

---

aws/eks-helm/argocd/locals.tf

feat: update argocd in_clusters

---

aws/alb/CHANGELOG.md
aws/alb/README.md
aws/alb/main.tf
aws/alb/security_group.tf
aws/alb/variables.tf

Add flag `enable_http_port` to add or ignore HTTP port 80 on security group and ALB listener.
To comply SOC2.
Add variable `enable_http_port`.
By default, it creates HTTP port listener on ALB and ingress rule on ALB security group.
When we disable the flag, it will ignore listening the port from ALB and remove the ingress rule from ALB security group.

AWS ALB: Add flag to manage config on HTTP port

---

aws/openvpn/CHANGELOG.md
aws/openvpn/README.md
aws/openvpn/sg.tf
aws/openvpn/variables.tf

Add variable `enabled_http_port` to make HTTP optional from security group.
To comply SOC2.
Add variable `enabled_http_port` to `aws_security_group_rule`
By default, it allows HTTP port ingress.
When disabled, it deny HTTP port ingress.

AWS Openvpn: add enabled_http_port

---

aws/rds/CHANGELOG.md
aws/rds/db_instance/main.tf
aws/rds/db_instance/variables.tf
aws/rds/main.tf

Add variable `multi-az` to indicate whether the database instance should be deployed across multiple availability zones

feat: add multi-az for database

---

CHANGELOG.md

* AWS Postgres [(./aws/postgres)](./aws/rds)
* Add variable `multi-az` to indicate whether the database instance should be deployed across multiple availability zones

release: v0.5.2

---

CHANGELOG.md

* AWS EKS: Helm Jenkins [(./aws/eks-helm/jenkins)](./aws/eks-helm/jenkins)
* Add `nodejs_configuration` to customize nodejs version in case projects need the latest version nodejs.
* Add `tolerations` and `node_selectors` for scheduling jenkins on managed node or fargate
* AWS EKS: Helm Jenkins [(./aws/eks-helm/jenkins)](./aws/eks-helm/jenkins)
* Update credential plugins version, which is the reason that cause crash for jenkins

release: v0.5.3

---

CHANGELOG.md
aws/eks-helm/opa/CHANGELOG.md
aws/eks-helm/opa/README.md
aws/eks-helm/opa/examples/README.md
aws/eks-helm/opa/examples/main.tf
aws/eks-helm/opa/main.tf
aws/eks-helm/opa/override.tofu
aws/eks-helm/opa/variables.tf
aws/eks-helm/opa/versions.tf

- Add OPA helm deployment module
- We (Project NineSuns) need to deploy this as a service in our EKS cluster, the service-platform pods should be able to call REST API to this service.

feat: Nguyen/add eks helm opa

---

aws/rds/CHANGELOG.md
aws/rds/README.md
aws/rds/db_instance/README.md
aws/rds/db_instance/main.tf
aws/rds/db_instance/variables.tf
aws/rds/main.tf
aws/rds/variables.tf

Add variable `primary_deletion_protection` and `replica_deletion_protection` to manage `deletion_protection` status on primary and replicas.
To enable `deletion_protection`, since default config would not protect instances from being deleted.
Add 2 variables `primary_deletion_protection` and `replica_deletion_protection`, default to `true`.
For primary instance, use `primary_deletion_protection`.
For replicas, they share the same `replica_deletion_protection`.

feat: add `deletion_protection` to AWS RDS instance

---

.github/CODEOWNERS
.pre-commit-config.yaml
CHANGELOG.md
README.md
aws/rds/CHANGELOG.md
aws/rds/README.md
aws/rds/db_instance/README.md
aws/rds/db_instance/main.tf
aws/rds/db_instance/outputs.tf
aws/rds/db_instance/variables.tf
aws/rds/examples/complete/outputs.tf
aws/rds/main.tf
aws/rds/outputs.tf
aws/rds/variables.tf

Added `db_port` as an output in both RDS and db_instance modules. This change exposes the database port, enabling easier access and integration with other resources.
- Eliminates the need for consumers to hardcode port values or look up ports manually.
- Enable better integration with other resources that need database connectivity information. 
- Added `db_port` output to the RDS module
- Added `db_port` output to the db_instance module

Add `db_port` output to `rds` module

---

.github/CODEOWNERS
.github/workflows/release.yml
CHANGELOG.md
aws/static-website/CHANGELOG.md

* AWS Static Website [(./aws/static-website)](./aws/static-website)
* Enable HTTP access for S3 bucket in CloudFront setup.

Release v0.6.3

---

CHANGELOG.md
aws/static-website/CHANGELOG.md
aws/static-website/s3.tf

Disable bucket policy creation for S3 bucket in `static-website` module.
- CloudFront module already handles the necessary bucket policies (See https://github.com/spartan-stratos/terraform-modules/blob/master/aws/static-website/modules/cloudfront/main.tf#L193).
- Removes duplicate S3 bucket policy creation from static-website module

Disable bucket policy creation for S3 bucket in `static-website` module.

---

CHANGELOG.md
aws/static-website/CHANGELOG.md

* AWS Static Website [(./aws/static-website)](./aws/static-website)
* Removes duplicate S3 bucket policy creation in [./aws/static-website/s3.tf](./aws/static-website/s3.tf).

Release: v0.6.4

---

CHANGELOG.md

* AWS Static-website [(./aws/static-website)](./aws/static-website)
* Add output `cloudfront_distribution_arn`.

release: v0.6.7

---

aws/ses-monitoring/CHANGELOG.md
aws/ses-monitoring/README.md
aws/ses-monitoring/dashboard.tf
aws/ses-monitoring/examples/complete/README.md
aws/ses-monitoring/examples/complete/main.tf
aws/ses-monitoring/lambda/main.js
aws/ses-monitoring/locals.tf
aws/ses-monitoring/main.tf
aws/ses-monitoring/variables.tf

Move SES monitoring to a separate module.
- **Single Responsibility Principle**: The current SES module handles both email sending configuration and monitoring, which violates the single responsibility principle.
- **Modularity**: Separating monitoring allows teams to optionally enable/disable email monitoring without affecting core SES functionality.
- **Testing**: Easier to test monitoring functionality in isolation.
Created new module `terraform-aws-ses-monitoring` that includes:
- SNS topic for SES notifications.
- Lambda function to process SES events.
- Datadog integration configuration

Move SES monitoring to a separate module

---

aws/oidc-provider/CHANGELOG.md
aws/oidc-provider/README.md
aws/oidc-provider/examples/complete/README.md
aws/oidc-provider/examples/complete/main.tf
aws/oidc-provider/examples/complete/outputs.tf
aws/oidc-provider/main.tf
aws/oidc-provider/outputs.tf
aws/oidc-provider/override.tofu
aws/oidc-provider/variables.tf
aws/oidc-provider/versions.tf

Move oidc-provider to a separate module.
- Moving to the Terraform Cloud registry
Created new module `terraform-aws-oidc-provider` to create a generic AWS OIDC Provider

Move oidc provider to a seperate module

---

datadog/oncall/CHANGELOG.md
datadog/oncall/README.md
datadog/oncall/examples/complete/README.md
datadog/oncall/examples/complete/main.tf
datadog/oncall/main.tf
datadog/oncall/outputs.tf
datadog/oncall/variables.tf
datadog/oncall/versions.tf
datadog/team/CHANGELOG.md
datadog/team/New_README
datadog/team/README.md
datadog/team/examples/complete/README.md
datadog/team/examples/complete/main.tf
datadog/team/main.tf
datadog/team/outputs.tf
datadog/team/variables.tf
datadog/team/versions.tf

Add datadog team & oncall modules
A fast, low-cost backup solution for on-call rotation notifications. Requires a one-time setup of the Datadog mobile app and an active internet connection.
Alert condition + message ⇒ Notification Rule ⇒ Oncall team  ⇒ Page Routing ⇒ Escalation Policy ⇒ Scheduled member
- Add team module to create Datadog team & add users
- Add on call module to create Page Routing, Escalation Policy, Schedule
Next step: 
- Write docs & usage guidance

add datadog oncall related modules

---

qdrant/accounts-cluster/CHANGELOG.md
qdrant/accounts-cluster/README.md
qdrant/accounts-cluster/examples/README.md
qdrant/accounts-cluster/examples/main.tf
qdrant/accounts-cluster/main.tf
qdrant/accounts-cluster/outputs.tf
qdrant/accounts-cluster/variables.tf
qdrant/accounts-cluster/versions.tf

The qdrant auth key resource are deprecated, so we have to update it to version 2 to make it compatible with newest version
I got this message while terraform plan, for that reason, I will update the auth key to v2 and update some relating variables
```
|
│ Warning: Deprecated Resource
│ 
│   with module.qdrant.qdrant-cloud_accounts_auth_key.this,
│   on .terraform/modules/qdrant/qdrant/main.tf line 13, in resource "qdrant-cloud_accounts_auth_key" "this":
│   13: resource "qdrant-cloud_accounts_auth_key" "this" {
│ 
│ The `qdrant-cloud_accounts_auth_key` resource is deprecated and will be removed in a future version. Please use the `qdrant-cloud_accounts_database_api_key_v2` resource instead.
│ 
│ (and one more similar warning elsewhere)
```

feat: update qdrant key resource to newest version

---

datadog/logging-monitor/CHANGELOG.md
datadog/logging-monitor/README.md
datadog/logging-monitor/examples/README.md
datadog/logging-monitor/examples/main.tf
datadog/logging-monitor/main.tf
datadog/logging-monitor/override.tofu
datadog/logging-monitor/variables.tf
datadog/logging-monitor/versions.tf

Add Datadog logging-monitor module.
2 monitors (that is filtered and categorized by Datadog WatchDog):
- High number of errors: Monitor if any issue have high number of errors found.
- New issue: Alert when a new issue found.
Based on live-monitor on project chargeFUZE. We use these as informative monitors to ensure on track with new error log pattern found.

feat: add Datadog logging-monitor module
