- aws/kms/README.md
- aws/kms/data.tf
- aws/kms/iam.tf
- aws/kms/variables.tf
Use `aws_caller_identity` to get `aws_account_id` instead of using a input variable
> update account_id retrieve

- aws/eks-cluster/CHANGELOG.md
- aws/eks-cluster/README.md
- aws/eks-cluster/datadog-rbac.tf
- aws/eks-cluster/iam.tf
- aws/eks-cluster/locals.tf
- aws/eks-cluster/modules/datadog-rbac/README.md
- aws/eks-cluster/modules/datadog-rbac/variables.tf
- aws/eks-cluster/outputs.tf
- aws/eks-cluster/variables.tf
- Add output datadog_agent_cluster_role_name to root module and remove default value of datadog_agent_cluster_role_name in submodule
- Change the assume policy of eks-node-cluster from eks.amazonaws.com to ec2.amazonaws.com
- Add output: necessary for bridgehealth adaption, since other resources relied on this output.
- Change assume policy: to match with bridgehealth-ai eks cluster, and document https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html. I don't understand why the original assume policy was  `eks.amazonaws.com` for the node role though.
> Update AWS eks-cluster module

- aws/postgres/CHANGELOG.md
- aws/postgres/main.tf
fix: correct AWS RDS condition error
* Correct conditions to create security group `aws_security_group.this` when variable `vpc_security_group_ids` is null.
Luckily, the usage of `var.vpc_security_group_ids` is working as expected so only redundant resources created, does not affect directly to the RDS's security group.
> fix: correct AWS RDS condition error

- aws/cloudwatch/alarm/CHANGELOG.md
- aws/cloudwatch/alarm/README.md
- aws/cloudwatch/alarm/main.tf
- aws/cloudwatch/alarm/variables.tf
- aws/openvpn/CHANGELOG.md
- aws/openvpn/README.md
- aws/openvpn/outputs.tf
- datadog/aws-monitor/examples/main.tf
- This update introduces the `instance_id` variable for EC2 alarms and ensures `InstanceId` is included when the namespace is "AWS/EC2". 
- Minor formatting adjustments were made in the example configuration for consistency.
Terraform plan
N/A
> Add support for EC2 InstanceId in CloudWatch alarm variables

- aws/openvpn/CHANGELOG.md
- aws/openvpn/README.md
- aws/openvpn/instance.tf
- aws/openvpn/variables.tf
- Introduced `http_tokens` and `http_endpoint` variables to control instance metadata service settings. 
([http_tokens](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#http_tokens-1) - (Optional) Whether or not the metadata service requires session tokens, also referred to as Instance Metadata Service Version 2 (IMDSv2). Valid values include optional or required.)
- Updated instance configurations to include these metadata options, enhancing control over metadata access and security.
- Default: 
Terraform plan
N/A
> Add metadata options configuration for EC2 instances

- aws/security-group/CHANGELOG.md
- aws/security-group/README.md
- aws/security-group/examples/complete/main.tf
- aws/security-group/security-group.tf
- Updated the logic to set from_port and to_port to -1 when the IP protocol is "-1", ensuring compatibility for security group rules with all protocols. 
Terraform Plan
N/A
> Handle "-1" IP protocol in from/to port values 

- aws/eks-helm/jenkins/CHANGELOG.md
- aws/eks-helm/jenkins/README.md
- aws/eks-helm/jenkins/main.tf
- aws/eks-helm/jenkins/variables.tf
* Add variable `jenkins_config_map_name` to use configMapRef in containerEnvFrom
* Add variable `jenkins_viewer` to add permission for GitHub team groups that defined in jenkins viewer
* 
> aws/jenkins: Add viewer group and config map name variables

- aws/oidc/provider/CHANGELOG.md
- aws/oidc/provider/main.tf
Fix `data.tls_certificate.this` use index because of it has "count" set
> fix index variables because of its count set

- aws/eks-helm/neo4j/CHANGELOG.md
- aws/eks-helm/neo4j/README.md
- aws/eks-helm/neo4j/examples/complete/main.tf
- aws/eks-helm/neo4j/main.tf
- Added configuration to use an existing secret for Neo4j authentication and set a password.
- Modified the ingress HTTP port to 7474 to align with Neo4j default settings. 
- > These changes enhance security and ensure proper application behavior.
Terraform Plan
N/A
> Set Neo4j auth secret and update ingress HTTP port

- aws/eks-helm/aws-load-balancer-controller/CHANGELOG.md
- aws/eks-helm/aws-load-balancer-controller/README.md
- aws/eks-helm/aws-load-balancer-controller/data.tf
- aws/eks-helm/aws-load-balancer-controller/locals.tf
- aws/eks-helm/aws-load-balancer-controller/main.tf
- aws/eks-helm/aws-load-balancer-controller/variables.tf
Add the `region variable` as optional, the default is null. If it is null, get the region by using `data aws_region`
N/A
https://www.notion.so/c0x12c/Terraform-Terraform-Modules-17901fb05bf180bda02bef71ebbed9f3?pvs=4
> feat: add the region variable as optional

- aws/elasticache/CHANGELOG.md
- aws/elasticache/README.md
- aws/elasticache/main.tf
- aws/elasticache/outputs.tf
Disable the Auth Token if `transit_encryption_enabled` is false
```
╷
│ Error: modifying ElastiCache Replication Group (service-platform) authentication: operation error ElastiCache: ModifyReplicationGroup, https response error StatusCode: 400, RequestID: 7ddae6b8-897f-4c7d-86f1-1c80f756b424, InvalidParameterValue: The AUTH token modification is only supported when encryption-in-transit is enabled.
│ 
│   with module.service_platform.module.redis.aws_elasticache_replication_group.this,
│   on .terraform/modules/service_platform.redis/aws/elasticache/main.tf line 26, in resource "aws_elasticache_replication_group" "this":
│   26: resource "aws_elasticache_replication_group" "this" {
│ 
╵
```
https://www.notion.so/c0x12c/Terraform-Terraform-Modules-17901fb05bf180bda02bef71ebbed9f3?pvs=4
> bug: fix auth token elasticache

- aws/github-self-hosted-runners/CHANGELOG.md
- aws/github-self-hosted-runners/README.md
- aws/github-self-hosted-runners/examples/complete/README.md
- aws/github-self-hosted-runners/examples/complete/main.tf
- aws/github-self-hosted-runners/examples/complete/outputs.tf
- aws/github-self-hosted-runners/examples/complete/terraform.tf
- aws/github-self-hosted-runners/main.tf
- aws/github-self-hosted-runners/outputs.tf
- aws/github-self-hosted-runners/scripts/bootstrap.tmpl
- aws/github-self-hosted-runners/variables.tf
- aws/github-self-hosted-runners/versions.tf
- Introduce a new Terraform module to manage GitHub Actions self-hosted runners on AWS. 
- Includes resources for EC2 instances, launch templates, auto-scaling groups, and example usage. 
Terraform Plan
https://app.vanta.com/tests/aws-kubernetes-cluster-control-plane-access-restricted
> Add Terraform module for GitHub Actions self-hosted runner

- aws/acm/CHANGELOG.md
- aws/acm/README.md
- aws/acm/main.tf
Update the ACM Validation `fqdn` value due to terraform apply issue
```
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/backbone.acm/aws/acm/main.tf line 51, in resource "aws_acm_certificate_validation" "this":
│   51:   validation_record_fqdns = flatten([aws_route53_record.validation[*].fqdn])
│ 
│ This object does not have an attribute named "fqdn".
╵
```
N/A
> bug: fix acm validation

- aws/eks-cluster/CHANGELOG.md
- aws/eks-cluster/cluster.tf
- The access_config block should be removed because modifying this setting triggers the recreation of the EKS cluster, which is disruptive.
Terraform
N/A
> Remove access_config block from EKS cluster

- aws/github-self-hosted-runners/CHANGELOG.md
- aws/github-self-hosted-runners/scripts/setup-environment.tmpl
- Previously, the script strictly installed the exact Terraform version. This update modifies the installation command to include version suffixes (which match with the syntax from version 1.4.3 and later)
https://developer.hashicorp.com/terraform/cli/install/apt#terraform-1-4-3-and-later
Terraform Plan
N/A
> Fix terraform installation syntax for ami

- aws/s3/CHANGELOG.md
- aws/s3/README.md
- aws/s3/iam.tf
- aws/s3/variables.tf
Allow to customize and add more policy for s3 read_write which can be required by different project
> feat: allow to add more permission to s3 policy

- aws/eks-cluster/CHANGELOG.md
- aws/eks-cluster/modules/managed-node-group/iam.tf
Remove AmazonEKS_CNI_IPv6_Policy policy and policy attachments.
This AWS managed policy isn't present, or was deprecated. It's not on the official list https://docs.aws.amazon.com/aws-managed-policy/latest/reference/policy-list.html
https://www.notion.so/EKS-Managed-Nodes-Dev-Rollout-workloads-to-managed-nodes-1ab4e7d2715780f5932ac6556731dde3
> fix eks managed nodes: remove AmazonEKS_CNI_IPv6_Policy policy

- aws/eks-cluster/CHANGELOG.md
- aws/eks-cluster/modules/managed-node-group/iam.tf
- aws/eks-cluster/modules/managed-node-group/main.tf
* Managed nodes: only add iam role policy when there is at least 1 statement
* Managed nodes: don't ignore desired_size
- Create IAM role policy error because there are no statements
- Couldn't update desired_size blocks us from update min_size and max_size because desired_size will not refresh and there is conditions ensure that min_size < desired_size < max_size. We don't need ignore_change because we don't refresh changes anyway.
https://www.notion.so/EKS-Managed-Nodes-Dev-Rollout-workloads-to-managed-nodes-1ab4e7d2715780f5932ac6556731dde3
> Fix eks-cluster managed nodes

- datadog/aws-monitor/CHANGELOG.md
- datadog/aws-monitor/elasticache.tf
`elasticache_cache_errors` is not neccessary to monitor, which don't have value to monitor
> fix: remove elasticache_cache_errors from aws_monitor

- aws/sqs/CHANGELOG.md
- aws/sqs/README.md
- aws/sqs/main.tf
- Ref: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_policy.html
- Added `version = "2012-10-17"` to explicitly define the AWS IAM policy document version in the SQS module.
Terraform Plan
> Set IAM policy document version in SQS module

- aws/eks-service/CHANGELOG.md
- aws/eks-service/README.md
- aws/eks-service/main.tf
Add the K8s service account annotation inline instead of separate to the `kubernetes_annotations`, it will help us remove the bug due to re-update the service account
- The Service account no have any changes when try to plan or apply
N/A
> bug: add inline k8s service account annotations

- aws/eks-service/main.tf
Revert kubenetes_annotations due to the default service account 
N/A
> feat: revert kubernetes_annotations for default service account

- datadog/service-monitor/CHANGELOG.md
- datadog/service-monitor/locals.tf
Modify the Datadog restart monitor to use the diff function, which captures only new restart events. When a pod restarts, the query returns a value of 1, and it falls back to 0 if no further restarts occur.
> feat: update query template for pod restarts
